routes/web.php
        Route::prefix('booking-stats')->name('booking-stats.')->group(function () {
            Route::get('/', BookingStatsController::class . '@index')->name('index');
        });

        Route::prefix('notification')->name('notification.')->group(function () {
            Route::get('/', NotificationController::class . '@index')->name('index');
            Route::post('/', NotificationController::class . '@update')->name('update');
            Route::get('/store', NotificationController::class . '@store')->name('store');
        });

        Route::prefix('broadcast-message')->name('broadcast-message.')->group(function () {
            Route::get('/', BroadcastMessageController::class . '@index')->name('index');
            Route::post('/', BroadcastMessageController::class . '@store')->name('store');
        });

        Route::prefix('setting')->name('setting.')->group(function () {
            Route::get('/', SettingController::class . '@index')->name('index');
            Route::post('/', SettingController::class . '@update')->name('update');
        });

        Route::prefix('home')->name('home.')->group(function () {
            Route::get('/', DashboardController::class . '@index')->name('index');
        });

        Route::prefix('dashboard')->name('dashboard.')->group(function () {
            Route::get('/', DashboardController::class . '@index')->name('index');
        });

        Route::get('/', function(){
            return redirect()->route('dashboard.index');
        });

        Route::prefix('profile')->name('profile.')->group(function () {
            Route::get('/', ProfileController::class . '@index')->name('index');
            Route::post('/', ProfileController::class . '@update')->name('update');
        });

        Route::prefix('user')->name('user.')->group(function () {
            Route::get('/', UserController::class . '@index')->name('index');
            Route::get('/{id}', UserController::class . '@show')->name('show');
            Route::post('/', UserController::class . '@update')->name('update');
            Route::post('/edit', UserController::class . '@edit')->name('edit');
            Route::get('/{id}/booking-log', BookingLogController::class . '@index')->name('booking-log.index');
            Route::get('/{id}/subscription-log', SubscriptionLogController::class . '@index')->name('subscription-log.index');
        });

        Route::prefix('flash-sale')->name('flash-sale.')->group(function () {
            Route::get('/', FlashSaleController::class . '@index')->name('index');
            Route::get('/create', FlashSaleController::class . '@create')->name('create');
            Route::get('/{id}', FlashSaleController::class . '@show')->name('show');
            Route::post('/', FlashSaleController::class . '@update')->name('update');
            Route::post('/store', FlashSaleController::class . '@store')->name('store');
        });

        Route::prefix('promo-code')->name('promo-code.')->group(function () {
            Route::get('/', PromoCodeController::class . '@index')->name('index');
            Route::get('/create', PromoCodeController::class . '@create')->name('create');
            Route::get('/{id}', PromoCodeController::class . '@show')->name('show');
            Route::get('/{code}/edit', PromoCodeController::class . '@edit')->name('edit');
            Route::put('/{code}', PromoCodeController::class . '@updatePromoCode')->name('updatePromoCode');
            Route::post('/', PromoCodeController::class . '@update')->name('update');
            Route::post('/store', PromoCodeController::class . '@store')->name('store');
        });

        Route::prefix('referral')->name('referral.')->group(function () {
            Route::get('/', ReferralController::class . '@index')->name('index');
            Route::get('/create', ReferralController::class . '@create')->name('create');
            Route::post('/', ReferralController::class . '@store')->name('store');
        });

        Route::prefix('feedback')->name('feedback.')->group(function () {
            Route::get('/', FeedbackController::class . '@index')->name('index');
            Route::get('/{id}', FeedbackController::class . '@show')->name('show');
        });

        Route::prefix('payment-log')->name('payment-log.')->group(function () {
            Route::get('/', PaymentLogController::class . '@index')->name('index');
            Route::get('/{id}', PaymentLogController::class . '@show')->name('show');
        });

        Route::prefix('booked-flight')->name('booked-flight.')->group(function () {
            Route::get('/', BookedFlightController::class . '@index')->name('index');
            Route::get('/{id}', BookedFlightController::class . '@show')->name('show');
        });

        Route::prefix('report')->name('report.')->group(function () {
            Route::get('/{type}', ReportController::class . '@index')->name('index');
        });

        Route::prefix('api-log')->name('api-log.')->group(function () {
            Route::get('/', ApiLogController::class . '@index')->name('index');
        });
    });
});


//Route::namespace('admin')->group(function () {
//    Route::get('/', 'LoginController@login')->name('home');
//    Route::post('/login', 'LoginController@login')->name('login');
//    Route::match(['get','post'],'/forget-password', 'LoginController@forgetPassword')->name('forget.password');
//    Route::match(['get','post'],'/recover-password/{token}', 'LoginController@recoverPassword')->name('recover.password');
//});
//
//Route::group(['namespace' => 'admin','middleware' => 'auth'],function(){
//    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
//    Route::match(['get','post'],'/changepassword', 'DashboardController@changePassword')->name('changepassword');
//    Route::match(['get','post'],'/editprofile', 'DashboardController@editProfile')->name('edit.profile');
//    Route::get('/logout', 'DashboardController@logout')->name('logout');
//
//    Route::group(['prefix' => '/user','as' => 'user.'],function(){
//        Route::get('/view/{id?}', 'UserController@view')->name('view');
//        Route::get('/change-status/{id}', 'UserController@changeStatus')->name('change-status');
//    });
//
//    Route::group(['prefix' => '/booking','as' => 'booking.'],function(){
//        Route::get('/view/{id?}', 'BookingController@view')->name('view');
//    });
//
//    Route::group(['prefix' => '/payment','as' => 'payment.'],function(){
//        Route::get('/account', 'PaymentController@accountPayments')->name('account');
//        Route::get('/flight', 'PaymentController@bookingPayments')->name('flight');
//    });
//
//    Route::match(['get','post'],'/commission', 'CommissionController@commission')->name('commission');
//
//    Route::group(['prefix' => '/exchange-rate','as' => 'exchange.rate.'],function(){
//        Route::get('/view', 'ExchangeRateController@view')->name('view');
//        Route::match(['get','post'],'/add', 'ExchangeRateController@add')->name('add');
//        Route::match(['get','post'],'/update/{id}', 'ExchangeRateController@update')->name('update');
//    });
//
////    Route::group(['prefix' => '/report','as' => 'report.'],function(){
////        Route::get('/account', 'ReportController@accountPayments')->name('account');
////        Route::get('/flight', 'ReportController@bookingPayments')->name('flight');
////    });
//});

Route::namespace('website')->name('website')->group(function () {

//    Route::get('/youtube', 'YoutubeController@index')->name('.youtube');
//    Route::post('/youtube', 'YoutubeController@store')->name('.youtube.store');
//    Route::get('/facebook', 'FacebookController@index')->name('.facebook');
//    Route::post('/facebook', 'FacebookController@store')->name('.facebook.store');

    Route::get('/about-us', 'StaticPagesController@aboutUs')->name('.about-us');
    Route::get('/customer-support', 'StaticPagesController@customerSupport')->name('.customer-support');
    Route::get('/faqs', 'StaticPagesController@faqs')->name('.faqs');
    Route::get('/terms-and-conditions', 'StaticPagesController@termsAndConditions')->name('.terms-and-conditions');
    Route::get('/privacy-policy', 'StaticPagesController@privacyPolicy')->name('.privacy-policy');
    Route::get('/refund-policy', 'StaticPagesController@refundPolicy')->name('.refund-policy');

    Route::prefix('/contact-us')->name('.contact-us')->group(function () {
        Route::get('/', 'ContactUsController@index');
        Route::post('/', 'ContactUsController@store');
    });

    Route::prefix('/manage-booking')->name('.manage-booking')->group(function () {
        Route::get('/', 'ManageBookingController@index');
        Route::post('/', 'ManageBookingController@show');
    });

    Route::prefix('/booking')->name('.booking')->group(function () {
        Route::post('/', 'BookingController@create');
        Route::post('/provision', 'BookingController@provisionBooking')->name('.provision');
        Route::post('/confirm', 'BookingController@confirmBooking')->name('.confirm');
    });

    Route::prefix('/search-flight')->name('.search-flight')->group(function () {
        Route::get('/', 'SearchFlightController@index');
    });

    Route::get('/test-booking',function(){
        $data['booking'] = \App\Booking::find(110);
        return view('website.booking.complete', $data);
    });

    foreach (['/', '/home'] as $prefix):
        Route::prefix($prefix)->name('.home')->group(function () {
            Route::get('/', 'HomeController@index');
        });
    endforeach;

    Route::group(['middleware' => ['auth', 'isUser']], function () {

        Route::prefix('/profile')->name('.profile')->group(function () {
            Route::get('/', 'ProfileController@index');
            Route::post('/', 'ProfileController@update');
            Route::post('/change-password', 'ProfileController@changePassword')->name('.change-password');
        });

app/Http/Controllers/web/PaymentLogController.php
<?php

namespace App\Http\Controllers\web;

use App\BookingPayment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaymentLogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['PaymentLog'] = BookingPayment::orderBy('id', 'desc')->get();
        return view('payment-log.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/payment-log/index.blade.php
@extends('layouts.app', ['Title' => 'Payment Log'])

@section('content')
    <div class="app-content content view user">
        <div class="content-wrapper">
            <div class="content-body">
                <section id="configuration" class="search view-cause">
                    <div class="row">
                        <div class="col-12">
                            <div class="card pad-20">
                                <div class="card-content collapse show">
                                    <div class="card-body table-responsive card-dashboard">
                                        <div class="row">
                                            <div class="col-12 d-block d-sm-flex justify-content-between">
                                                <div class="left">
                                                    <h1 class="pull-left">Payment Log</h1>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mt-2 filter-main justify-content-between">
                                            <div class="col-12">
                                                <label>Sort By:</label>
                                            </div>
                                            <div class="col-lg-6 col-md-12 col-sm-12">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6  form-group">
                                                        <label for="">From:</label>
                                                        <input id="fromSelector" type="text" readonly="">
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6  form-group">
                                                        <label for="">To:</label>
                                                        <input id="toSelector" type="text" readonly="">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row maain-tabble mt-3">
                                            <table class="table table-striped table-bordered zero-configuration">
                                                <thead>
                                                <tr>
                                                    <th>S.no</th>
                                                    <th>Booked On</th>
                                                    <th>User</th>
                                                    <th>Booking ID</th>
                                                    <th>Amount (Before Discount)</th>
                                                    <th>Discount Applicable</th>
                                                    <th>Amount (After Discount)</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($PaymentLog as $key => $value)
                                                    <tr>
                                                        <td>{{ $key + 1 }}</td>
                                                        <td>{{ $value->created_at }}</td>
                                                        <td>
                                                            <a href="{{ route('user.show',['id' => $value->booking->user_id]) }}"><u>{{ $value->booking->user->profile->first_name }}</u></a>
                                                        </td>
                                                        <td>
                                                            <a href="{{ route('booked-flight.show',['id' => $value->booking->id]) }}"><u>{{ $value->booking->id}}</u></a>
                                                        </td>
                                                        <td>{{ $value->booking->fare }}</td>
                                                        <td>{{ $value->booking->discount }}</td>
                                                        <td>{{ $value->fares }}</td>
                                                    </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection

resources/views/payment-log/show.blade.php
@extends('layouts.app', ['Title' => 'Payment Log Details'])

@section('content')

@endsection